---
name: Repository Request
description: Request a new repository in your organization.
title: "Repository Request"
labels: [repo-request]
body:
  - type: markdown
    attributes:
      value: |
        🥳 We love to see you getting started with a new project!
        
        This form and process was created to make sure we can help you as quickly as possible while keeping our governance and compliance on track.
        
        Please fill out the following information to request a new repository in our organization. Once you submit the form the repository will be created automatically with some basic best practices in place.
  - type: dropdown
    attributes:
      label: Visibility
      options:
        - public
        - internal
        - private
      default: 2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Organization
      description: The organization that owns this repository
      options:
        - burns-harbor
        - butler
        - cleveland
        - coatesville
        - columbus
        - conshohocken
        - coshocton
        - Dearborn
        - indiana-harbor
        - mansfield
        - middletown
        - riverdale
        - rockport
        - steelton
        - tek-kote
        - weirton
        - zanesville
    validations:
      required: true
  - type: input
    attributes:
      label: Name
      description: Name of the Repository
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Team
      options:
        - first-team
        - second-team
    validations:
      required: true