host: github.com
issue-labels:
  - name: repo-request
    description: Issues that are requesting a new repository to be created
    color: 51829B
  - name: team-membership-request
    description: Issues that are requesting new user membership for the organization
    color: 51829B