team:
  first-team: ft
  second-team: st
organization:
  burns-harbor: bhw
  butler:	buw
  cleveland: clw
  coatesville:	ctv
  columbus:	cco
  conshohocken:	epl
  coshocton:	csw
  Dearborn:	dbw
  indiana-harbor:	ihe
  mansfield: maw
  middletown:	miw
  riverdale: rvd
  rockport:	rpw
  steelton:	stn
  tek-kote: itk
  weirton: wrt
  zanesville:	zaw
