name: Handle Issue Form

on: 
  issues:
    types:
      - labeled

permissions:
  contents: read
  actions: write
  issues: write

jobs:  
  on-repository-request:
    name: "Repository Request"
    if: github.event.label.name == 'repo-request'
    secrets: inherit
    uses: ./.github/workflows/handle-repository-creation.yml
    with:
      visibility: private
  on-team-membership-request:
    name: "Team Membership Request"
    if: github.event.label.name == 'team-membership-request'
    secrets: inherit
    uses: ./.github/workflows/handle-team-membership-request.yml
