name: Handle Issue Form

on: 
  issues:
    types:
      - labeled

permissions:
  contents: read
  actions: write
  issues: write

jobs:  
  on-repository-request:
    name: "Repository Request"
    if: github.event.label.name == 'repo-request'
    secrets: inherit
    uses: ./.github/workflows/handle-repository-creation.yml
    with:
      visibility: private