name: Initialising Octodesk

on:
  create:
  workflow_dispatch: 

permissions:
  contents: read
  issues: write

jobs:
  initialise:
    name: Initialise Octodesk
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONFIG_FILE: config/general.yml
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create Configured Labels
        run: |
          length=$(yq e '.issue-labels | length' $CONFIG_FILE)
          for ((i=0; i<$length; i++))
            do
              name=$(yq e ".issue-labels[$i].name" $CONFIG_FILE)
              color=$(yq e ".issue-labels[$i].color" $CONFIG_FILE)
              description=$(yq e ".issue-labels[$i].description" $CONFIG_FILE)
              gh label create "$name" -d "$description" -c "$color" -f
            done


    